### ISSUE TITLE
Update content and favicon

### ISSUE THREAD

**Issue by Chill-City-Technology** [raidotaxi/raido-web#3]
Update footer content to - All rights reserved by Raido Powered by CHILL CITY TECHNOLOGY Private Limited

Update Service Page content to - At Raido, we make commuting affordable and convenient in Chennai. Our bike and auto taxi services are designed to offer the lowest rates around. Whether you're heading to work or exploring the city, we ensure you travel without high costs. With clear and transparent pricing, there are no hidden fees. Bike taxi owners pay just 20 INR per day, while auto taxi owners pay 30 INR per day. Enjoy unlimited rides with zero commission, meaning all your earnings stay with you. Choose Raido for an economical and efficient travel experience, and keep more of what you earn.

Update Favicon with. - 
![favicon](https://github.com/user-attachments/assets/f997db4e-d2e1-460b-8102-5376a72cd7c1)

**Comment by midhun-developer** [comment]
https://github.com/raidotaxi/raido-web/pull/4
https://github.com/raidotaxi/raido-web/pull/5

Changes are done and deployed.

**Comment by Chill-City-Technology** [comment]
Great! Closing this Issue
